gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Emerald Hope!\p"
	.string "My name is BIRCH, the\n"
	.string "Pokémon PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "That's enough about me though.\p"
	.string "Tell me about yourself!$"

gText_Birch_BoyOrGirl::
	.string "How do you prefer to look?\n"
	.string "Option 1 or 2?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "...\p"
	.string "... hi!\n"
	.string "this is maddie, creator of emerald hope!\p"
	.string "hope is ostensibly a difficulty hack,\n"
	.string "although it reaches beyond that.\p"
	.string "more specificially, to create a healthy\n"
	.string "metagame for competitive singles,\l"
	.string "although doubles was also in scope.\p"
	.string "the game itself is still fully\n"
	.string "playable and includes thorough\l"
	.string "quality of life features.\p"
	.string "the heart of the hack is a testing\n"
	.string "ground and source of experience for\l"
	.string "a much more ambitious hack to come.\p"
	.string "as the changes in this hack are far\n"
	.string "too numerous to list here, please\l"
	.string "refer to the provided documentation.\p"
	.string "have fun, experiment thoroughly,\n"
	.string "and most importantly, trans rights!\p"
	.string "$"
