Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "Accessed Someone's PC.$"

gText_StorageSystemOpened:: @ 82726A3
	.string "Pokémon Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "Accessed Lanette's PC.$"
