Route102_EventScript_ItemPotion::
	finditem ITEM_RARE_CANDY
	end

Route103_EventScript_ItemGuardSpec::
	finditem ITEM_CHERISH_BALL
	end

Route103_EventScript_ItemPPUp::
	finditem ITEM_CHERISH_BALL
	end

Route104_EventScript_ItemPPUp::
	finditem ITEM_CHERISH_BALL
	end

Route104_EventScript_ItemPokeBall::
	finditem ITEM_CHERISH_BALL
	end

Route104_EventScript_ItemXAccuracy::
	finditem ITEM_CHERISH_BALL
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_CHERISH_BALL
	end

Route105_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route106_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp::
	finditem ITEM_CHERISH_BALL
	end

Route109_EventScript_ItemPotion::
	finditem ITEM_CHERISH_BALL
	end

Route110_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route110_EventScript_ItemDireHit::
	finditem ITEM_CHERISH_BALL
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_CHERISH_BALL
	end

Route111_EventScript_ItemTMSandstorm::
	finditem ITEM_TM_SANDSTORM
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_CHERISH_BALL
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_CHERISH_BALL
	end

Route113_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_CHERISH_BALL
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_NUGGET
	end

Route115_EventScript_ItemSuperPotion::
	finditem ITEM_CHERISH_BALL
	end

Route115_EventScript_ItemTMFocusPunch::
	finditem ITEM_TM_FOCUS_PUNCH
	end

Route115_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route115_EventScript_ItemGreatBall::
	finditem ITEM_CHERISH_BALL
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_CHERISH_BALL
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_CHERISH_BALL
	end

Route116_EventScript_ItemXSpecial::
	finditem ITEM_CHERISH_BALL
	end

Route116_EventScript_ItemEther::
	finditem ITEM_CHERISH_BALL
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_ItemPotion::
	finditem ITEM_CHERISH_BALL
	end

Route117_EventScript_ItemGreatBall::
	finditem ITEM_CHERISH_BALL
	end

Route117_EventScript_ItemRevive::
	finditem ITEM_CHERISH_BALL
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_CHERISH_BALL
	end

Route119_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_CHERISH_BALL
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_CHERISH_BALL
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_CHERISH_BALL
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_CHERISH_BALL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_CHERISH_BALL
	end

Route121_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive::
	finditem ITEM_CHERISH_BALL
	end

Route121_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route123_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_CHERISH_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_CHERISH_BALL
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_CHERISH_BALL
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_CHERISH_BALL
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_CHERISH_BALL
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemMaxRevive::
	finditem ITEM_CHERISH_BALL
	end

PetalburgCity_EventScript_ItemEther::
	finditem ITEM_CHERISH_BALL
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_CHERISH_BALL
	end

RustboroCity_EventScript_ItemXDefend::
	finditem ITEM_NUGGET
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack::
	finditem ITEM_NUGGET
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_CHERISH_BALL
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_NUGGET
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_TM66
	end

RusturfTunnel_EventScript_ItemPokeBall::
	finditem ITEM_CHERISH_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther::
	finditem ITEM_CHERISH_BALL
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	finditem ITEM_CHERISH_BALL
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	finditem ITEM_CHERISH_BALL
	end

GraniteCave_B2F_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

GraniteCave_B2F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

JaggedPass_EventScript_ItemBurnHeal::
	finditem ITEM_NUGGET
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTMToxic::
	finditem ITEM_TM_TOXIC
	end

MeteorFalls_1F_1R_EventScript_ItemTMIronTail::
	finditem ITEM_TM23
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
	finditem ITEM_CHERISH_BALL
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP::
	finditem ITEM_CHERISH_BALL
	end

MeteorFalls_B1F_2R_EventScript_ItemTMDragonClaw::
	finditem ITEM_TM51
	end

NewMauville_Inside_EventScript_ItemUltraBall::
	finditem ITEM_CHERISH_BALL
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	finditem ITEM_CHERISH_BALL
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_CHERISH_BALL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_CHERISH_BALL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_CHERISH_BALL
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTMIceBeam::
	finditem ITEM_TM_ICE_BEAM
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_NUGGET
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTMRainDance::
	finditem ITEM_TM_RAIN_DANCE
	end

ScorchedSlab_EventScript_ItemTMSunnyDay::
	finditem ITEM_TM_SUNNY_DAY
	end

SafariZone_Northwest_EventScript_ItemTMSolarBeam::
	finditem ITEM_TM_SOLAR_BEAM
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_CHERISH_BALL
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_CHERISH_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTMShadowBall::
	finditem ITEM_TM_SHADOW_BALL
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTMSkillSwap::
	finditem ITEM_TM48
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_CHERISH_BALL
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_NUGGET
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTMHail::
	finditem ITEM_TM_HAIL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTMEarthquake::
	finditem ITEM_TM_EARTHQUAKE
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_NUGGET
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	finditem ITEM_CHERISH_BALL
	end

VictoryRoad_B1F_EventScript_ItemTMPsychic::
	finditem ITEM_TM_PSYCHIC
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_NUGGET
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_CHERISH_BALL
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_CHERISH_BALL
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	finditem ITEM_CHERISH_BALL
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_CHERISH_BALL
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_CHERISH_BALL
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_CHERISH_BALL
	end

LittleRoot_EventScript_ItemOranBerry::
	finditem ITEM_ORAN_BERRY
	end


LittleRoot_EventScript_ItemLumBerry::
	finditem ITEM_LUM_BERRY
	end

Route101_EventScript_GrassKnot::
	finditem ITEM_TM92
	end

Route101_EventScript_EnergyBall::
	finditem ITEM_TM67
	end
